steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/simple-code-reviewer", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/simple-code-reviewer"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "simple-code-reviewer"
      - "--image"
      - "gcr.io/$PROJECT_ID/simple-code-reviewer"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "simple-code-reviewer@$PROJECT_ID.iam.gserviceaccount.com"
images:
  - "gcr.io/$PROJECT_ID/simple-code-reviewer"
